INSERT INTO `products` (`product_id`, `merchant_id`, `name`, `description`, `price`, `image_url`, `stock`) VALUES
(81, 16, 'Signature Phat Kaphrao', 'A Thai stir-fry with minced meat, chili, and holy basil, served with rice and a fried egg.', 11.50, 'phatkaphrot.png', 20),
(82, 16, 'Pad Thai', 'Classic Thai stir-fried rice noodles with tamarind sauce, tofu, shrimp or chicken, bean sprouts, and crushed peanuts.', 10.00, 'padthai.png', 20),
(83, 16, 'Tomyum Soup with Rice (Chicken)', 'A hot and sour Thai soup flavored with lemongrass, lime, and chili, served with steamed rice.', 10.00, 'tom-yum-soup.png', 20),
(84, 16, 'Tomyum Soup with Rice (Seafood)', 'A hot and sour Thai soup flavored with lemongrass, lime, and chili, served with steamed rice.', 13.00, 'tom-yum-soup.png', 20),
(85, 16, 'Signature Soya Ice with Taro Balls', 'Refreshing chilled soy milk topped with chewy taro balls for a light, sweet treat.', 10.50, 'TaroBalls.png', 20),
(86, 16, 'Thai Boba Milk Tea', 'Creamy Thai-style milk tea with chewy tapioca pearls for a rich, refreshing drink.', 10.90, 'thai_milk_tea.jpg', 20),
(87, 17, 'Yang Zhou Fried Rice', 'Fragrant fried rice with shrimp, eggs, vegetables, and a touch of soy for classic Chinese flavor.', 10.00, 'yangchow.png', 20),
(88, 17, 'Chinese Sausage Fried Rice', 'Savory fried rice with sweet and smoky Chinese sausage, eggs.', 10.00, 'sausagerice.png', 20),
(89, 17, 'Korean Cold Noodles', 'Chewy noodles served chilled in a tangy, refreshing broth with vegetables and egg.', 12.00, 'coldnoodles.jpeg', 20),
(90, 17, 'Fried Beef Hor Fun', 'Stir-fried flat rice noodles with tender beef slices, bean sprouts, and soy sauce wok aroma.', 9.00, 'beefhorfun.jpeg', 20),
(91, 17, 'Fried Mi Hun', 'Light and flavorful stir-fried rice vermicelli with vegetables and savory seasoning.', 9.00, 'mihun.jpg', 20),
(92, 17, 'Yam Milk Tea', 'Smooth milk tea blended with sweet yam flavor, served with chewy pearls.', 8.00, 'yammilktea.png', 20),
(93, 18, 'Pan Mee Dry', 'Hand-pulled noodles tossed with soy sauce, minced pork, anchovies, and fried shallots.', 8.50, 'panmeedry.png', 20),
(94, 18, 'Pan Mee Soup', 'Comforting noodle soup with hand-pulled noodles, minced pork, vegetables, and crispy anchovies.', 8.50, 'panmeesoup.png', 20),
(95, 18, 'Ipoh Chicken Hor Fun', 'Silky flat noodles in a light chicken broth, topped with poached chicken and chives.', 10.00, 'ipohhorfun.png', 20),
(96, 18, 'Hainan Fried Chicken', 'Crispy golden fried chicken marinated with Hainanese spices, juicy inside and crunchy outside.', 10.50, 'hainam_chicken.png', 20),
(97, 18, 'Hainan Coffee', 'Bold and aromatic traditional Hainanese-style black coffee.', 4.50, 'coffee.jpg', 20),
(98, 18, 'Hainan Cham', 'A rich, balanced mix of Hainanese coffee and milk tea.', 4.50, 'cham.png', 20),
(99, 20, 'Mushroom Chicken Dumpling', 'Juicy chicken dumplings mixed with earthy mushrooms, wrapped and steamed or pan-fried.', 8.00, 'mushchick.png', 20),
(100, 20, 'Onion Chicken Dumpling', 'Savory chicken filling blended with sweet onions for a flavorful bite.', 8.00, 'chickendum.png', 20),
(101, 20, 'Chives Pork Dumpling', 'Classic pork dumplings with fresh Chinese chives for a fragrant taste.', 9.00, 'porkchieve.png', 20),
(102, 20, 'Sour Spicy Noodle', 'Tangy and spicy noodle soup with chili, vinegar, and rich broth for a bold kick.', 10.00, 'suanlafen.png', 20),
(103, 20, 'Braised Beef Noodle', 'Hearty noodles served with tender braised beef in aromatic soy-based broth.', 12.00, 'braisedbeef.jpeg', 20),
(104, 21, 'Waffle', 'Golden, crispy outside and fluffy inside, perfect with syrup or ice cream.', 4.50, 'chocowaffle.png', 20),
(105, 21, 'Kopi O', 'Bold black coffee, strong and smooth, served the traditional way.', 3.00, 'kopio.png', 20),
(106, 21, 'Teh Tarik', 'Malaysia’s famous pulled tea, creamy and frothy with rich flavor.', 4.00, 'tehtarik.png', 20),
(107, 21, 'Watermelon Juice', 'Freshly blended watermelon, sweet and refreshing.', 6.00, 'watermelon.png', 20),
(108, 21, 'Mango Juice', 'Smooth, tropical mango juice with natural sweetness.', 6.00, 'mango.png', 20),
(109, 22, 'Chrysanthemum Tea', 'Light and floral herbal tea, naturally cooling and soothing for the body.', 5.00, 'chry.png', 20),
(110, 22, 'Luo Han Guo Tea', 'Sweet and refreshing monk fruit tea, perfect for relieving thirst and heat.', 6.00, 'luohanguo.png', 20),
(111, 22, 'Five Flower Tea', 'A fragrant blend of five Chinese flowers, known for cooling and detoxifying effects.', 5.00, '5flower.png', 20),
(112, 22, 'Prunella Tea', 'Mildly bitter-sweet herbal tea made with self-heal flowers, believed to ease heatiness.', 5.00, 'prunella.png', 20),
(113, 22, 'Licorice & Mint Tea', 'Cooling mint balanced with sweet licorice root, refreshing and calming.', 5.00, 'licorice.png', 20),
(114, 23, 'Ham Egg Sandwich', 'Soft sandwich bread layered with ham, fluffy egg, and light seasoning.', 7.80, 'ham_egg.jpeg', 20),
(115, 23, 'Luncheon Meat Egg Sandwich', 'Classic Hong Kong–style sandwich with fried luncheon meat and egg.', 7.80, 'luncheon.jpg', 20),
(116, 23, 'HK Curry Chicken Rice', 'Steamed rice served with tender chicken in rich Hong Kong–style curry sauce.', 9.80, 'curry_chick.png', 20),
(117, 23, 'HK Curry Pork Rice', 'Fragrant rice with pork slices simmered in mildly spicy HK curry sauce.', 9.80, 'currypork.jpeg', 20),
(118, 23, 'Curry Fish Ball', 'Bouncy fish balls simmered in flavorful curry gravy, a true HK street snack.', 6.00, 'curry-fishball.jpg', 20),
(119, 25, 'Korean Fried Chicken', 'Crispy fried chicken coated in Korean-style sweet & spicy sauce.', 17.00, 'korean_chick.png', 20),
(120, 25, 'Japanese Ramen', 'Rich broth with springy noodles, topped with chashu, egg, and vegetables.', 12.90, 'ramen.png', 20),
(121, 25, 'Carbonara', 'Creamy pasta with smoky bacon, egg, parmesan, and black pepper.', 12.90, 'carbonara.jpeg', 20),
(122, 25, 'Curry Udon', 'Thick udon noodles served in savory Japanese curry with vegetables and meat.', 10.90, 'curry_udon.jpeg', 20),
(123, 25, 'Creamy Tomato Spaghetti', 'Spaghetti tossed in a creamy tomato sauce with herbs and cheese.', 13.00, 'creamy_tomato.jpeg', 20),
(124, 26, 'Grilled Lemongrass Chicken', 'Juicy chicken thigh marinated with lemongrass, garlic, and spices, grilled to golden perfection and served with coconut rice and spicy sambal.', 17.00, 'lemongrass_chick.jpg', 20),
(125, 26, 'Seafood Laksa', 'Rich coconut-based laksa broth with prawns, fish slices, and clams, served with rice noodles and bean sprouts.', 14.00, 'seafood_laksa.jpeg', 20),
(126, 26, 'Astana Beef Rendang Pasta', 'A fusion of traditional Malay beef rendang with Italian pasta. Tender beef slow-cooked in coconut milk and spices for a unique East-meets-West flavor.', 18.00, 'beefrendang.jpg', 20),
(127, 26, 'Truffle Mushroom Fried Rice', 'Fragrant fried rice infused with mushrooms and truffle oil, topped with crispy garlic and fresh herbs.', 20.00, 'truffle.jpg', 20),
(128, 26, 'Choco-Banana Waffle Delight', 'Crispy Belgian waffle topped with caramelized bananas, chocolate sauce, and a scoop of vanilla ice cream.', 12.90, 'waffle.jpeg', 20),
(129, 27, 'Teriyaki Chicken Bowl', 'Grilled chicken glazed with teriyaki sauce, served on sushi rice with fresh veggies and sesame seeds.', 17.00, 'teriyaki_chicken.png', 20),
(130, 27, 'Salmon Bowl', 'Fresh salmon sashimi slices on sushi rice, topped with edamame, seaweed salad, and pickled ginger.', 14.00, 'salmon_bowl.png', 20),
(131, 27, 'Protein Bowl', 'A power-packed mix of grilled chicken, boiled egg, tofu, and quinoa rice for a balanced, high-protein meal.', 18.00, 'protein.jpeg', 20),
(132, 27, 'Tempura Prawn Bowl', 'Crispy tempura prawns served on sushi rice with shredded cabbage, seaweed, and a drizzle of tempura sauce.', 20.00, 'tempura.jpg', 20),
(133, 27, 'Seafood Bowl', 'A combination of salmon, prawns, and squid on sushi rice, paired with seaweed salad and miso dressing.', 12.90, 'seafood.jpg', 20),
(134, 28, 'Matcha Mexico Bun', 'Soft Mexican-style bun with a crisp matcha cookie crust, fluffy inside and lightly sweet.', 3.90, 'matchamexico.jpg', 20),
(135, 28, 'Coffee Mexico Bun', 'Fragrant bun topped with a coffee-flavored crust, warm and buttery inside.', 3.90, 'mexicancoffee.png', 20),
(136, 28, 'Hot Dog Bun', 'Classic soft bun filled with juicy sausage, baked to golden perfection.', 2.90, 'sausagebun.jpg', 20),
(137, 28, 'Chicken Floss Bun', 'Fluffy bun generously topped with savory chicken floss and creamy mayo.', 3.50, 'chickenfloss.png', 20),
(138, 28, 'Tuna Sandwich', 'Fresh sandwich filled with tuna mayo, lettuce, and cucumber in soft bread slices.', 3.90, 'tuna_sandwich.jpg', 20),
(139, 30, 'Salted Egg Potato Chips', 'Crispy potato chips coated with rich salted egg yolk seasoning, savory and addictive.', 7.90, 'salted_egg.jpeg', 20),
(140, 30, 'Bottle Mineral Water', 'Pure and refreshing mineral water, perfect for hydration anytime.', 2.50, 'mineral_water.jpeg', 20),
(141, 30, 'Kitkat Chocolate', 'Crispy wafer fingers coated in smooth milk chocolate — a classic sweet treat.', 3.50, 'kitkat.png', 20),
(142, 30, 'Dutch Lady Milk (Choco)', 'Creamy chocolate-flavored milk, rich in calcium and perfect as an energy boost.', 4.20, 'choco.jpeg', 20),
(143, 30, 'Maggie Curry Noodle Cup', 'Instant curry-flavored noodles with bold spices, ready in just 3 minutes.', 3.80, 'maggie.jpeg', 20),
(144, 31, 'Colgate Toothpaste (120g)', 'Fluoride toothpaste for fresh breath and strong teeth.', 7.90, 'colgate.jpeg', 20),
(145, 31, 'Lifebuoy Body Wash (500ml)', 'Antibacterial body wash that keeps skin clean and refreshed.', 12.50, 'lifebuoy.jpeg', 20),
(146, 31, 'Pantene Shampoo (340ml)', 'Nourishing shampoo for smooth, shiny, and healthy-looking hair.', 15.90, 'pantene.jpeg', 20),
(147, 31, 'Dettol Antibacterial Wipes (50 sheets)', 'Convenient disinfecting wipes for hands and surfaces, kills 99.9% germs.', 8.90, 'dettol.jpeg', 20),
(148, 31, 'Scott Kitchen Towel (2 Rolls)', 'Strong and absorbent paper towels for everyday kitchen cleaning.', 6.50, 'kitchentowel.jpeg', 20),
(149, 24, 'Waffle', 'Golden, crispy outside and fluffy inside, perfect with syrup or ice cream.', 4.50, 'chocowaffle.png', 20),
(150, 24, 'Kopi O', 'Bold black coffee, strong and smooth, served the traditional way.', 3.00, 'kopio.png', 20),
(151, 24, 'Teh Tarik', 'Malaysia’s famous pulled tea, creamy and frothy with rich flavor.', 4.00, 'tehtarik.png', 20),
(152, 24, 'Watermelon Juice', 'Freshly blended watermelon, sweet and refreshing.', 6.00, 'watermelon.png', 20),
(153, 24, 'Mango Juice', 'Smooth, tropical mango juice with natural sweetness.', 6.00, 'mango.png', 20),
(154, 29, 'KitKat Chocolate Bar', 'Crispy wafer coated in milk chocolate', 3.50, 'kitkat.png', 20),
(155, 29, 'Oreo Cookies Pack', 'Chocolate sandwich cookies with cream filling', 4.50, 'oreo.jpeg', 20),
(156, 29, 'Pocky Strawberry', 'Biscuit sticks coated with strawberry cream', 5.00, 'pocky.jpeg', 20),
(157, 29, 'Snickers Bar', 'Chocolate bar with nougat, caramel, and peanuts', 3.80, 'snickers.jpeg', 20),
(158, 29, 'Twisties Cheese Snack', 'Cheese-flavored crunchy corn snack', 2.50, 'twistie.jpeg', 20),
(159, 19, 'Lanzhou Beef Noodles', 'Signature hand-pulled noodles with clear beef broth and slices of beef', 13.00, 'lanzhou.jpeg', 20),
(160, 19, 'Braised Beef Noodles', 'Rich broth with slow-cooked beef chunks and hand-pulled noodles', 15.00, 'braisedbeef.jpeg', 20),
(161, 19, 'Chicken Ramen', 'Hand-pulled noodles served in chicken broth with tender chicken slices', 12.00, 'chicken.jpeg', 20),
(162, 19, 'Cold Liangpi', 'Chewy cold noodles with sesame paste, cucumber, and chili oil', 8.00, 'coldliangpi.jpeg', 20),
(163, 19, 'Plum Juice', 'Traditional sour plum drink, sweet and refreshing', 5.00, 'plum.jpeg', 20),
(164, 35, 'Vegetarian Spaghetti', 'A wholesome plate of spaghetti cooked with fresh vegetables and herbs, offering a light yet flavorful vegetarian delight.', 12.90, 'vege_spaghetti.jpg', 30),
(165, 35, 'Chicken Bolognese', 'Classic Italian-style spaghetti served with rich tomato sauce and minced chicken, slow-cooked for a comforting and hearty taste.', 12.90, 'bolognese.jpg', 35),
(166, 35, 'Butter Milk Chicken Rice', 'Crispy fried chicken coated in creamy, aromatic buttermilk sauce, served with steamed rice — a Malaysian favorite!', 12.90, 'buttermilk.jpg', 130),
(167, 35, 'Gold Carbonara', 'Creamy pasta infused with cheese, egg yolk, and a hint of garlic — a rich and satisfying twist on the classic carbonara.', 12.90, 'carbonara_spa.jpg', 230),
(168, 35, 'Chicken Katsu', 'Golden-breaded chicken cutlet, crispy on the outside and tender inside, served with fragrant rice and savory sauce.', 12.90, 'chicken_katsu.jpg', 230),
(169, 33, 'Cantonese Hor Fun', 'Silky flat rice noodles in eggy gravy with seafood, meat, and vegetables.', 8.00, 'cantonese_horfun.jpg', 100),
(170, 33, 'SinChew Mi Hun', 'Fragrant stir-fried rice vermicelli with shrimp, meat, eggs, and vegetables in savory soy sauce.', 8.00, 'sinchew_bihun.jpg', 100),
(171, 33, 'Fried Kueh Tiew', 'Wok-fried flat rice noodles with eggs, bean sprouts, chives, and your choice of meat or seafood.', 8.00, 'kuehtiew.jpg', 100),
(172, 33, 'Traditional Pan Mee', 'Hand-pulled noodles in light soup with minced pork, mushrooms, anchovies, and vegetables.', 9.00, 'panmee.jpg', 100),
(173, 33, 'Bitter Gourd Pan Mee', 'Pan mee served with slices of bitter gourd in a flavorful broth, refreshing and slightly bitter.', 9.00, 'bittergourd.jpg', 100);
